[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/starter-kit"
  to = "/hemp-starter-kit"
  status = 301
  force = false
  query = {path = ":path"}