backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
site_url: https://www.elevatedtrading.com/
display_url: https://www.elevatedtrading.com/
logo_url: https://www.elevatedtrading.com/img/apple-touch-icon.png

collections:
  - name: "products"
    label: "Products"
    folder: "src/pages/products"
    create: true
    slug: "{{slug}}"
    preview_path: "products/{{slug}}"
    fields:
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: true}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-details"}
      - {label: "Product Image", name: product_image, widget: "image", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Category", name: "category", widget: "select", multiple: false, options: ["Flower", "Concentrate"], required: true, default: "Flower"}
      - {label: "THC %", name: "thc", widget: "number", valueType: "float", required: true}
      - {label: "CBD %", name: "cbd", widget: "number", valueType: "float", required: true}
      - {label: "Weights", name: weights, widget: list, collapsed: true, fields: [{ label: "Weight", name: weight, widget: object, collapsed: true, fields: [ {label: "Value", name: value, widget: "number", required: true },{label: "Metric", name: metric, widget: "select", multiple: false, options: ["lb", "kg"], default: "lb", required: true}]} ]}
      - {label: "COA Link", name: "coa_link", widget: "string", required: true}
      - {label: "Featured", name: featured, widget: object, collapsed: true, fields: [ {label: "Is Featured", name: isFeatured, widget: boolean, default: false},{ label: "Text", name: text, widget: "string", default: false, }]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
