backend:
  name: git-gateway
  branch: master
media_folder: static/media
public_folder: /media
site_url: https://www.elevatedtrading.com/
display_url: https://www.elevatedtrading.com/
logo_url: https://www.elevatedtrading.com/media/apple-touch-icon.png
publish_mode: editorial_workflow

collections:
  - name: 'products'
    label: 'Products'
    folder: 'src/pages/products'
    label_singular: 'Product'
    create: true
    editor:
      preview: false
    slug: '{{slug}}'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    preview_path: 'products/{{slug}}/index'
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Meta Description',
          name: 'meta_description',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'product-details',
        }
      - {
          label: 'Product Image',
          name: 'imageInfo',
          widget: 'object',
          fields:
            [
              {
                label: 'Image',
                name: 'image',
                widget: 'image',
                required: true,
              },
              { label: 'Alt', name: 'alt', widget: 'string' },
            ],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          multiple: false,
          options:
            ['Flower', 'Concentrate', 'Edible', 'Vape', 'Tincture', 'Smokable'],
          required: true,
          default: 'Flower',
        }
      - {
          label: '∆9-THC %',
          name: 'thc',
          widget: 'number',
          valueType: 'float',
          required: true,
        }
      - {
          label: 'CBD %',
          name: 'cbd',
          widget: 'number',
          valueType: 'float',
          required: true,
        }
      - {
          label: 'Weight',
          name: 'weights',
          widget: 'list',
          fields:
            [
              { label: 'Value', name: 'value', widget: 'number' },
              {
                label: 'Metric',
                name: 'metric',
                widget: 'select',
                multiple: false,
                options: ['lb', 'kg'],
                default: 'lb',
                required: true,
              },
            ],
        }
      - { label: 'COA Upload', name: 'coa_link', widget: 'file' }
      # - { label: 'Details', name: 'details', widget: 'object', fields: [
      #         # { label: 'Description', name: 'description', widget: 'markdown' },
      #         {
      #           label: 'Info',
      #           name: 'info',
      #           widget: 'list',
      #           required: true,
      #           fields:
      #             [
      #               {
      #                 label: 'Label',
      #                 name: 'label',
      #                 widget: 'string',
      #                 required: true,
      #               },
      #               {
      #                 label: 'Items',
      #                 name: 'items',
      #                 widget: 'list',
      #                 required: true,
      #                 fields:
      #                   [
      #                     {
      #                       label: 'Item',
      #                       name: 'item',
      #                       widget: 'string',
      #                       required: true,
      #                     },
      #                   ],
      #               },
      #             ],
      #         },
      #       ] }
      - { label: 'Description', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - {
              label: 'Hero',
              name: 'hero',
              widget: 'object',
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: 'string' },
                  {
                    label: 'Background Image',
                    name: 'backgroundImg',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Alt', name: 'alt', widget: 'string' },
                      ],
                  },
                ],
            }
          - {
              label: 'Product Section',
              name: 'products',
              widget: 'object',
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                ],
            }
          - {
              label: 'Rogue Valley Section',
              name: 'rogueValley',
              widget: 'object',
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                ],
            }
          - {
              label: 'ETC Values Section',
              name: 'etcValues',
              widget: 'object',
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                  {
                    label: 'Background Image',
                    name: 'backgroundImg',
                    widget: 'image',
                  },
                  {
                    label: 'Values',
                    name: 'values',
                    widget: 'list',
                    allow_add: false,
                    fields:
                      [
                        { label: 'Value', name: 'value', widget: 'string' },
                        {
                          label: 'Description',
                          name: 'description',
                          widget: 'text',
                        },
                      ],
                  },
                ],
            }
          - {
              label: 'Farm Section',
              name: 'farming',
              widget: 'object',
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                  {
                    label: 'Background Image',
                    name: 'backgroundImg',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Alt', name: 'alt', widget: 'string' },
                      ],
                  },
                ],
            }
          - {
              label: 'Supply Chain Section',
              name: 'supplyChain',
              widget: 'object',
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                ],
            }
          - {
              label: 'Footer',
              name: 'footer',
              widget: 'object',
              fields:
                [
                  { label: 'Blurb', name: 'blurb', widget: 'text' },
                  { label: 'Legal', name: 'legal', widget: 'text' },
                ],
            }
          - {
              label: 'Subscription info',
              name: 'subscription',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Background Image',
                    name: 'backgroundImg',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Alt', name: 'alt', widget: 'string' },
                      ],
                  },
                  {
                    label: 'Callouts',
                    name: 'callouts',
                    widget: 'list',
                    fields:
                      [
                        { label: 'Title', name: 'value', widget: 'string' },
                        {
                          label: 'Description',
                          name: 'description',
                          widget: 'text',
                        },
                      ],
                  },
                ],
            }
          - {
              label: 'Shipping info',
              name: 'shipping',
              widget: 'object',
              fields:
                [{ label: 'Description', name: 'description', widget: 'text' }],
            }
      - file: 'src/pages/starter-kit.md'
        label: 'Starter Kit'
        name: 'starter-kit'
        fields:
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - {
              label: 'Meta Description',
              name: 'meta_description',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'starter-kit',
            }
          - {
              label: 'Product Image',
              name: 'product_image',
              widget: 'image',
              required: true,
            }
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - {
              label: 'Quantity',
              name: 'quantities',
              widget: 'list',
              fields: [{ label: 'Value', name: 'value', widget: 'number' }],
            }
          - {
              label: 'Included items',
              name: 'included',
              widget: 'list',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                  {
                    label: 'Background Image',
                    name: 'backgroundImg',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Alt', name: 'alt', widget: 'string' },
                      ],
                  },
                ],
            }
          - {
              label: 'Kit Value',
              name: 'kitValue',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Background Image',
                    name: 'backgroundImg',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Alt', name: 'alt', widget: 'string' },
                      ],
                  },
                  {
                    label: 'Callouts',
                    name: 'callouts',
                    widget: 'list',
                    fields:
                      [
                        { label: 'Title', name: 'value', widget: 'string' },
                        {
                          label: 'Description',
                          name: 'description',
                          widget: 'text',
                        },
                      ],
                  },
                ],
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/lab-results.md'
        label: 'Lab Results'
        name: 'lab-results'
        fields:
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - {
              label: 'Meta Description',
              name: 'meta_description',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'lab-results',
            }
          - {
              label: 'Hero',
              name: 'hero',
              widget: 'object',
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: 'string' },
                  {
                    label: 'Description',
                    name: 'description',
                    widget: 'string',
                  },
                  {
                    label: 'Background Image',
                    name: 'backgroundImg',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Alt', name: 'alt', widget: 'string' },
                      ],
                  },
                ],
            }
      - file: 'src/pages/policies.md'
        label: 'Policies'
        name: 'policies'
        fields:
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - {
              label: 'Meta Description',
              name: 'meta_description',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'policies',
            }
          - {
              label: 'Hero',
              name: 'hero',
              widget: 'object',
              fields: [{ label: 'Heading', name: 'heading', widget: 'string' }],
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    label_singular: 'Blog'
    create: true
    editor:
      preview: false
    slug: '{{slug}}'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    preview_path: 'blog/{{slug}}/index'
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Meta Description',
          name: 'meta_description',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - {
          label: 'Product Image',
          name: 'product_image',
          widget: 'image',
          required: true,
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Topics',
          name: 'blogTags',
          widget: 'select',
          multiple: true,
          options:
            [
              'CBD',
              'Concentrate',
              'Hemp Flower',
              'Retail',
              'Manufacturing',
              'Delta 8',
              'Legal',
            ],
          required: true,
          default: 'CBD',
        }
      - {
          label: 'Featured',
          name: 'is_featured',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown' }
#  - name: 'blog'
#     label: 'Blog'
#     folder: 'src/pages/blog'
#     slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
#     fields:
#       - {
#           label: 'Template Key',
#           name: 'templateKey',
#           widget: 'hidden',
#           default: 'blog-post',
#         }
#       - { label: 'Title', name: 'title', widget: 'string' }
#       - { label: 'Publish Date', name: 'date', widget: 'datetime' }
#       - { label: 'Description', name: 'description', widget: 'text' }
#       - { label: 'Body', name: 'body', widget: 'markdown' }
#       - { label: 'Tags', name: 'tags', widget: 'list' }
